import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import ToDoApp from "../components/ToDoApp";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ToDoApp />
      </main>

      {/* <footer className={styles.footer}>
        Created by: Nitin Rana
        <Link href="https://www.linkedin.com/in/nitin-rana2004/"></Link>
      </footer> */}
    </div>
  );
}
